### ISSUE TITLE
Disable RTL_433 and just run MQTT Auto Discovery

### ISSUE THREAD

**Issue by murkumurdok** [DanielWinks/HassOS-Addons#12]
Hi, I have a feature request for an unconventional use-case:  I am running rtl_433 on a separate machine because my HassOS VM was having some usb issues with the RTL2832U.  I modified the rattler config to just subscribe to the events published by the other rtl_433 instance and it has been working well.  I do it this way because, frankly, I think your device creation script works better than anyone else's.  That being said, the built-in rtl_433 keeps running in the background and throwing up errors that no device is found.  I don't think it's having a negative impact on HA other than filling up log entries, but I'm wondering how difficult it would be to implement a config option to disable the internal rtl_433 server.  This would help people like me that prefer not to/can't run RTL on their HA machine.

**Comment by murkumurdok** [comment]
Thanks very much. Take your time.

**Comment by DanielWinks** [comment]
Alright, the latest version has an option that disables the running of rtl_433 within the Docker container. It still ends up running the s6 stuff, so the container still keeps running (and using a couple MB of RAM and like 0.01% CPU), but at least it's not hammering the logs with error messages. I'll have to look to see if there's a way to make S6 exit entirely if there's no running services, but that's a task for another day.

**Comment by murkumurdok** [comment]
Awesome, thanks for your work!
