### ISSUE TITLE
Devices section not optional in configuration page

### ISSUE THREAD

**Issue by grunthos503** [DanielWinks/HassOS-Addons#14]
The Devices section is supposed to be optional, but the configuration page requires the Devices section to be filled in, when attempting to save changes for other settings.

Attempting to save settings with an empty Devices section gives the following error:

` Failed to save add-on configuration, Invalid list for option 'devices' in Rattler 433 (6172d6c4_rtl_433_hassio). Got {'mqtt_prefix': 'rtl_433', 'ha_discovery_topic': 'homeassistant', 'retain': True, 'enable_internal_rtl433': False, 'customize': {'active': False, 'folder': 'rattler'}, 'mqtt_host': 'mqtt.zzzz', 'mqtt_port': 1883, 'mqtt_user': 'mqtt', 'mqtt_pass': 'zzzzzzzz', 'devices': {}} `

**Comment by DanielWinks** [comment]
Yeah, I'll have to figure out how to make this truly optional.

Hopefully over the winter here I'll have time to improve this, or just add a full UI to select/add devices, rather than using a config section.

**Comment by DanielWinks** [comment]
Closing this as I am no longer maintaining this add-on (I've moved my home automation to Hubitat and no longer use Home Assistant).
