### ISSUE TITLE
Update RTL-433 to 21.12

### ISSUE THREAD

**Issue by Triberg** [DanielWinks/HassOS-Addons#8]
I have a device that was only added to RTL-433 in release 21.12: https://github.com/merbanan/rtl_433/releases/tag/21.12

It looks like this plugin is using rtl_433 version 21.05 (2020-05-09).  Can it be updated to the latest version (21.12)?

**Comment by DanielWinks** [comment]
Updated rtl_433 to 21.12. Let me know if there's any changes needed to the config generator to accommodate your device.
