### ISSUE TITLE
Adding custom protocols

### ISSUE THREAD

**Issue by unclebacon-live** [DanielWinks/HassOS-Addons#9]
I am attempting to add custom protocols over and above the default ones via the customize folder. I had to manually create the required folders in the share directory ('rattler' and 'rattler/flex'). Inside the flex folder exists a pr.conf containing additional protocols to add however this error shows in the log upon restart:
`./run: line 58: [: bashio::fs.directory_exists: unary operator expected`
Hope to get this working!

**Comment by DanielWinks** [comment]
Fixed with https://github.com/DanielWinks/HassOS-Addons/commit/4318a8b071f3a08b282cec274b16a4680aa133f9
